kind: Application
apiVersion: capabilities.3scale.net/v1beta1
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "3"
  name: application-sample
  namespace: threescale
spec:
  accountCR:
    name: developeraccount1
  applicationPlanName: plan01
  description: 'testing application'
  name: testApp
  productCR:
    name: product1
  suspend: false
#  serviceRef:
#    name: product1
# userKey: "your-user-key"  
